### ISSUE TITLE
9.5 installed and started

### ISSUE THREAD

**Issue by schors** [gitinsky/ansible-role-postgresql#1]
Install and run version of Postgres 9.5. 
Probably

**Comment by hryamzik** [comment]
What's wrong with `postgres_version: 9.5`?

**Comment by schors** [comment]
Nothing. But README :)

**Comment by hryamzik** [comment]
It's there in variables and 9.5 is not mentioned as tested for a reason. If it works fine for you just make a PR. I'm closing this issue.
